### ISSUE TITLE
BOLTSFC is not compatible with Python 3

### ISSUE THREAD

**Issue by normandc** [berndhahnebach/BOLTSFC#4]
start_bolts.FCMacro does not launch on FreeCAD 0.18.1 when using Python 3.

The following error is printed in the report view.

```
Traceback (most recent call last):
  File "/home/user/.FreeCAD/Macro/start_bolts.FCMacro", line 1, in <module>
    import BOLTS
  File "/home/user/.FreeCAD_orig/Mod/BOLTSFC/BOLTS/__init__.py", line 21, in <module>
    import bolttools.blt
<class 'ModuleNotFoundError'>: No module named 'bolttools'
```
OS: Ubuntu 18.04.2 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.1.
Build type: Release
Python version: 3.6.7
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: French/Canada (fr_CA)

**Comment by berndhahnebach** [comment]
```
Traceback (most recent call last):
  File "C:/Users/BHA/AppData/Roaming/FreeCAD/Mod/Macros/start_bolts.FCMacro", line 1, in <module>
    import BOLTS
  File "C:\Users\BHA\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\__init__.py", line 21, in <module>
    import bolttools.blt
<class 'ModuleNotFoundError'>: No module named 'bolttools'
```

confirmed on 

OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16093 (Git)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 690774c0effe4fd7b8d2b5e2fb2b8c8d145e21ce
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Switzerland (de_CH)

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=10&t=36186

**Comment by berndhahnebach** [comment]
fixed ... you need FreeCAD above 0.19.16694 https://github.com/FreeCAD/FreeCAD/commit/cd74f2e92908e94f9f7bc718e1be52939647b844


![Screenshot_20190510_215048](https://user-images.githubusercontent.com/6129869/57553671-80254100-736f-11e9-8e18-090d7b091543.png)
